---
- name: Continuous Running Ansible Playbook with Website Ping
  hosts: localhost
  gather_facts: false
  vars:
    interval_seconds: 300  # Adjust the interval based on your needs

  tasks:
    - name: Display Message
      debug:
        msg: "This playbook is running continuously."
      async: "{{ interval_seconds }}"
      poll: 0
      until: false  # To ensure the task runs indefinitely
