---
- name: Continuous Display Message Ansible Playbook
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Display Message Infinitely
      debug:
        msg: "This message will be displayed continuously."

    - name: Infinite Loop
      command: sleep 5
      loop: "{{ range(1, 4294967295) }}"
      loop_control:
        pause: 5
      when: "'infinite' in ansible_loop_var"
